### ISSUE TITLE
GitHub Page Set Up

### ISSUE THREAD

**Issue by aprilrpil** [aprilrpil/mms142-grouph-2022.github.io#2]
Hi, @sasha-g-reyes!

## 1
Please create a Project table or board for the group's repository.

Tips for the project feature:
[Learning about Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)
[Quickstart for Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects)
[Adding Projects to repository](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/adding-your-project-to-a-repository)

## 2
Github's Wiki feature is only available to public repositories for Github Free accounts and organizations,
so can you see if changing the repository's visibility to 'public' will make a Wiki tab appear in our repo?

## Thank you!
And Thanks for creating the group's repository!

_Originally posted by @aprilrpil in https://github.com/sasha-g-reyes/mms142-grouph-2022/issues/1#issuecomment-1349096042_
      
---

## P.S.
@sasha-g-reyes  Kindly rename the repository name after changing the visibility settings to public
with 'mms142-grouph-2022.github.io' to create GitHub Pages. You can follow instructions in the link below to "activate" or "deploy" our website and change the site's title and description:
[https://docs.github.com/en/pages/quickstart](https://docs.github.com/en/pages/quickstart)

## PPS
Lastly, please add some description to the repository's Description box, as well.
Not the one in the configuration text file or *config.yml*; the one in the dashboard, in `<> Code` tab. Any description will do as a draft.

Thank you!

**Comment by sasha-g-reyes** [comment]
Done with:
Project table
Changing visibility to public
Renaming Repository

**Comment by aprilrpil** [comment]
> Done with: Project table Changing visibility to public Renaming Repository

Thank you, sasha!

**Comment by aprilrpil** [comment]
https://user-images.githubusercontent.com/75361345/207668475-3e140422-4991-42cb-9627-4b25b1b856f5.mp4

Hi @sasha-g-reyes! I'm hoping you can add a project table to the repository as I can't do it from my end. And also edit the repository's description -- please add the link of our Github Page's site as the repo's website link. You refer to this video as an example:
